# Generated by Django 2.2.7 on 2019-12-10 19:44

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0002_auto_20191211_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_data',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
