# Generated by Django 2.2.7 on 2019-12-10 20:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0003_auto_20191211_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_data',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
