# Generated by Django 2.2.7 on 2019-12-10 21:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0005_auto_20191211_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_data',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
